#!/usr/bin/env bash
# load balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy 
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 13125-web-01 18.207.4.84 check\n\tserver 13125-web-02 3.215.79.123:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
